name: tests

on:
  push:
  pull_request:

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: latest
          extensions: mbstring
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer update -q
      - name: Test
        run: vendor/bin/phpunit
